In [1]:
%pip install pandas faker streamlit plotly scikit-learn

Requirement already satisfied: pandas in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: faker in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (37.12.0)
Requirement already satisfied: streamlit in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (1.50.0)
Requirement already satisfied: plotly in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (6.6.0)
Requirement already satisfied: scikit-learn in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.22.4 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from pandas) (2025.3)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (8.1.8)
Requirement already satisfied: packaging<26,>=20 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (25.0)
Requirement already satisfied: pillow<12,>=7.1.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (11.3.0)
Requirement already satisfied: protobuf<7,>=3.20 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (6.33.5)
Requirement already satisfied: pyarrow>=7.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (4.15.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (3.1.46)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (0.9.1)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from streamlit) (6.5.5)
Requirement already satisfied: jinja2 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.1)
Requirement already satisfied: narwhals>=1.14.2 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.18.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from requests<3,>=2.27->streamlit) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from requests<3,>=2.27->streamlit) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: scipy>=1.6.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.27.1)
Requirement already satisfied: six>=1.5 in /Users/pierson.chu/Downloads/github/KYC_risk_profiling_dashboard/.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
import random
from faker import Faker
import os

# Initialize Faker and set seeds for reproducibility
fake = Faker()
Faker.seed(42)
random.seed(42)

# Define pools of data, intentionally including high-risk scenarios
nationalities = ['USA', 'UK', 'Canada', 'Panama', 'Cayman Islands', 'North Korea', 'Singapore', 'Australia']
occupations = ['Software Engineer', 'Teacher', 'Casino Operator', 'Accountant', 'Cash-Intensive Business Owner', 'Doctor', 'Freelancer']

# Generate 100 customer records
mock_data = []
for _ in range(100):
    customer = {
        # .unique ensures it never generates the exact same ID twice.
        # bothify tells it to replace specific symbols: # gets replaced by a random number (0-9), and ? gets replaced by a random letter (A-Z).
        # So, CUST-####-???? turns into something like CUST-4921-XPLQ.
        'Customer_ID': fake.unique.bothify(text='CUST-####-????'), # e.g., CUST-1234-ABCD
        'Age': random.randint(18, 85),
        'Nationality': random.choice(nationalities),
        'Occupation': random.choice(occupations),
        'Estimated_Annual_Income': random.randint(20000, 500000)
    }
    mock_data.append(customer)

# Convert to a Pandas DataFrame
df_kyc = pd.DataFrame(mock_data)

# Ensure the data directory exists (just in case)
os.makedirs('../data', exist_ok=True)

# Save the dataset to the 'data' folder
csv_path = '../data/mock_kyc_data.csv'
df_kyc.to_csv(csv_path, index=False)

print(f"Successfully generated {len(df_kyc)} records and saved to {csv_path}")

# Preview the first 5 rows
df_kyc.head()

Successfully generated 100 records and saved to ../data/mock_kyc_data.csv

,Customer_ID,Age,Nationality,Occupation,Estimated_Annual_Income
0,CUST-1043-oiVg,32,USA,Doctor,164194
1,CUST-8196-cbfn,49,Panama,Teacher,406123
2,CUST-3890-JmTP,31,UK,Cash-Intensive Business Owner,241208
3,CUST-8637-LrZa,22,USA,Software Engineer,134629
4,CUST-2654-jnWv,47,USA,Cash-Intensive Business Owner,124248

In [ ]:
# testing function
import sys

# sys.path is literally just a Python list containing all the folder paths that Python is allowed to look inside when trying to find a module.
# a double dot .. is shorthand for "go up one folder" (to the parent directory).
# A single dot . means "my current folder."
# Essentially saying "Hey, add the folder one level up to your approved search list."

# aml-compliance-dashboard/      <-- By appending '..', you told Python to look here!
# │
# ├── kyc_rules_engine.py        <-- Python finds it!
# │
# └── notebooks/                 
#     └── generate_mock_data.ipynb  <-- You are currently running code here
    
sys.path.append('..') 

from kyc_rules_engine import process_kyc_data

scored_df = process_kyc_data(df_kyc)
print(scored_df['Risk_Tier'].value_counts())
scored_df[scored_df['Risk_Tier'] == 'High'].head()

Risk_Tier
High      49
Low       29
Medium    22
Name: count, dtype: int64

,Customer_ID,Age,Nationality,Occupation,Estimated_Annual_Income,Risk_Tier
1,CUST-8196-cbfn,49,Panama,Teacher,406123,High
5,CUST-1161-wwMq,71,Panama,Accountant,328944,High
8,CUST-3413-gyrD,37,Panama,Freelancer,196472,High
10,CUST-1928-UpkD,63,North Korea,Cash-Intensive Business Owner,158685,High
13,CUST-9537-zPDj,64,Panama,Doctor,56466,High